CREATE TABLE IF NOT EXISTS "Stores" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"street" VARCHAR(150) NOT NULL,
	"building_number" VARCHAR(5) NOT NULL,
	"postal_code" VARCHAR(6) NOT NULL CHECK(postal_code ~ '^[0-9]{2}-[0-9]{3}$')),
	"city" VARCHAR(30) NOT NULL,
	"status" VARCHAR(9) NOT NULL CHECK(status IN ('OPEN', 'SUSPENDED', 'CLOSED')),
	"opening_date" DATE NOT NULL,
	"suspension_date" DATE,
	"closure_date" DATE,
	"phone_number" VARCHAR(15) CHECK(phone_number ~ '^[0-9]{2}-[0-9]{3}-[0-9]{2}-[0-9]{2}$' OR phone_number ~ '^[0-9]{3}-[0-9]{3}-[0-9]{3}$'),
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Store_Opening_Hours" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"store_id" INTEGER NOT NULL,
	"day_of_week" VARCHAR(12) NOT NULL,
	"opening_time" TIME NOT NULL,
	"closing_time" TIME NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Bakery_Products" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL,
	"description" VARCHAR(500),
	"category" VARCHAR(20) NOT NULL,
	"unit_of_measure" VARCHAR(5) NOT NULL,
	"recipe_creation_date" DATE,
	"status" VARCHAR(15) NOT NULL CHECK(status IN ('ACTIVE', 'DISCONTINUED')),
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Product_Authors" (
	"employee_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"bakery_product_id" INTEGER NOT NULL,
	PRIMARY KEY("employee_id", "bakery_product_id")
);

CREATE TABLE IF NOT EXISTS "Product_Prices" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"bakery_product_id" INTEGER,
	"price" NUMERIC(10,2),
	"valid_from" DATE,
	"valid_to" DATE NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Transactions" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"unit_price" NUMERIC(10,2) NOT NULL,
	"quantity" INTEGER NOT NULL,
	"document_type" VARCHAR(10) NOT NULL CHECK(document_type IN ('RECEIPT', 'INVOICE')),
	"document_number" VARCHAR(30) NOT NULL,
	"purchase_timestamp" TIMESTAMP NOT NULL,
	"bakery_product_id" INTEGER NOT NULL,
	"store_id" INTEGER NOT NULL,
	"employee_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Transaction_Cancellations" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"transaction_id" INTEGER NOT NULL,
	"quantity" INTEGER NOT NULL,
	"amount" NUMERIC(10,2) NOT NULL,
	"cancellation_timestamp" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Employees" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"first_name" VARCHAR(50) NOT NULL,
	"last_name" VARCHAR(50) NOT NULL,
	"PESEL" VARCHAR(11) NOT NULL UNIQUE,
	"street" VARCHAR(150) NOT NULL,
	"building_number" VARCHAR(5) NOT NULL,
	"apartment_number" VARCHAR(5),
	"postal_code" VARCHAR(6) NOT NULL CHECK(postal_code ~ '^[0-9]{2}-[0-9]{3}$')),
	"city" VARCHAR(30) NOT NULL,
	"employment_start_date" DATE NOT NULL,
	"contract_end_date" DATE,
	"store_id" INTEGER NOT NULL,
	"email" VARCHAR(50) CHECK(email LIKE '%@%'),
	"phone_number" VARCHAR(15) CHECK(phone_number ~ '^[0-9]{2}-[0-9]{3}-[0-9]{2}-[0-9]{2}$' OR phone_number ~ '^[0-9]{3}-[0-9]{3}-[0-9]{3}$'),
	"employment_type" VARCHAR(30) NOT NULL CHECK(employment_type IN ('EMPLOYMENT_CONTRACT', 'MANDATE_CONTRACT', 'CONTRACT_FOR_SPECIFIC_WORK')),
	"position_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Positions" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Employees_Audit" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"employee_id" INTEGER,
	"first_name" VARCHAR(50) NOT NULL,
	"last_name" VARCHAR(50) NOT NULL,
	"PESEL" VARCHAR(11) NOT NULL UNIQUE,
	"street" VARCHAR(150) NOT NULL,
	"building_number" VARCHAR(5) NOT NULL,
	"apartment_number" VARCHAR(5),
	"postal_code" VARCHAR(6) NOT NULL CHECK(postal_code ~ '^[0-9]{2}-[0-9]{3}$')),
	"city" VARCHAR(30) NOT NULL,
	"employment_start_date" DATE NOT NULL,
	"contract_end_date" DATE,
	"store_id" INTEGER NOT NULL,
	"email" VARCHAR(50) CHECK(email LIKE '%@%'),
	"phone_number" VARCHAR(15) CHECK(phone_number ~ '^[0-9]{2}-[0-9]{3}-[0-9]{2}-[0-9]{2}$' OR phone_number ~ '^[0-9]{3}-[0-9]{3}-[0-9]{3}$'),
	"employment_type" VARCHAR(30) NOT NULL CHECK(employment_type IN ('EMPLOYMENT_CONTRACT', 'MANDATE_CONTRACT', 'CONTRACT_FOR_SPECIFIC_WORK')),
	"position_id" INTEGER NOT NULL,
	"valid_from" DATE,
	"valid_to" DATE NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Product_Stock" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"bakery_product_id" INTEGER NOT NULL,
	"store_id" INTEGER NOT NULL,
	"quantity_in_stock" INTEGER NOT NULL CHECK(quantity_in_stock >= 0),
	"last_updated" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Product_Stock_History" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"product_stock_id" INTEGER NOT NULL,
	"quantity_before" INTEGER NOT NULL CHECK(quantity_in_stock >= 0),
	"quantity_change" INTEGER NOT NULL CHECK(quantity_change <> 0),
	"change_code" VARCHAR(30) NOT NULL,
	"employee_id" INTEGER NOT NULL,
	"change_timestamp" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Dictionary" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"group_code" VARCHAR(20) NOT NULL,
	"code" VARCHAR(30) NOT NULL,
	"name" VARCHAR(100) NOT NULL,
	PRIMARY KEY("id")
);

ALTER TABLE "Store_Opening_Hours"
ADD FOREIGN KEY("store_id") REFERENCES "Stores"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Product_Authors"
ADD FOREIGN KEY("bakery_product_id") REFERENCES "Bakery_Products"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Product_Prices"
ADD FOREIGN KEY("bakery_product_id") REFERENCES "Bakery_Products"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Transactions"
ADD FOREIGN KEY("bakery_product_id") REFERENCES "Bakery_Products"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Transactions"
ADD FOREIGN KEY("store_id") REFERENCES "Stores"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Transaction_Cancellations"
ADD FOREIGN KEY("transaction_id") REFERENCES "Transactions"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Employees"
ADD FOREIGN KEY("store_id") REFERENCES "Stores"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Employees"
ADD FOREIGN KEY("position_id") REFERENCES "Positions"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Employees_Audit"
ADD FOREIGN KEY("employee_id") REFERENCES "Employees"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Employees_Audit"
ADD FOREIGN KEY("store_id") REFERENCES "Stores"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Employees_Audit"
ADD FOREIGN KEY("position_id") REFERENCES "Positions"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Product_Stock"
ADD FOREIGN KEY("bakery_product_id") REFERENCES "Bakery_Products"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Product_Stock_History"
ADD FOREIGN KEY("product_stock_id") REFERENCES "Product_Stock"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Product_Stock_History"
ADD FOREIGN KEY("employee_id") REFERENCES "Employees"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Product_Stock_History"
ADD FOREIGN KEY("change_code") REFERENCES "Dictionary"("code")
ON UPDATE NO ACTION ON DELETE NO ACTION;